I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "game/achievement_screen.rpy", line 110, in set_default
    default achievement_notification_list = []
Exception: store.achievement_notification_list is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3753, in execute_default_statement
    i.set_default(start)
  File "game/achievement_screen.rpy", line 110, in set_default
    default achievement_notification_list = []
Exception: store.achievement_notification_list is being given a default a second time.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
VNBE 1.0
Sun Jan 30 14:05:31 2022
